config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :auths
  get '/forgot_password', to: 'passwords#forgot'
  post 'send_token', to: 'passwords#send_token'

  namespace :api do
    # auth
    resources :auths, only: :show
    get '/auths_by_email', to: 'auths_by_emails#show', as: :auths_by_email
    # kanban_assignee
    get '/kanban_assignees', to: 'kanban_assignees#get_assignees'
    post '/kanban_assignees/assign', to: 'kanban_assignees#assign'
  end

  resources :accounts
  resource :profile, only: %i[show update]

  # kanban
  resources :kanbans
  patch '/kanbans/:id/sort', to: 'kanbans#sort', as: 'kanban_sort'

  # kanban column
  resources :kanban_columns

  # card
  resources :cards

  # card comment
  resources :card_comments

  root 'home#index'
end

app/models/card.rb
class Card < ApplicationRecord
  validates :title, presence: true
  belongs_to :kanban_column
  has_many :card_comments
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_auth!
  before_action :set_instances, only: %i[ show update destroy ]
  before_action only: %i[ create update destroy ] do
    authorized_assignees?(card_params)
  end

  def show
    @card_comments = CardComment.where(card_id: @card.id)
  end

  def create
    # authorized_assignees?(card_params['kanban_column_id'])
    @card = Card.new(card_params)
    respond_to do |format|
      if @card.save!
        return unless request.referrer.present?

        format.html { redirect_to request.referrer, notice: "#{@card.title} was created!" }
        format.json { render json: @card, status: :created }
      else
        flash[:error] = "#{@card.name} couldn't created. Something went wrong!"
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @card.update!(card_params)
        format.html { redirect_to card_path(@card), notice: "#{@card.title} card was updated!" }
      else
        flash[:error] = "#{@card.title} couldn't update. Something went wrong!"
        format.html { redirect_to card_path(@card) }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    Card.destroy(@card.id)
    respond_to do |format|
      if response.successful?
        format.html { redirect_to kanban_path(@kanban_column.kanban_id),
                                  notice: "#{@card.title} card was delete!" }
      else
        flash[:error] = "#{@card.title} couldn't delete. Something went wrong!"
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_instances
    @card = Card.find(params[:id])
    @kanban_column = KanbanColumn.find(@card.kanban_column_id)
  end

  def card_params
    params.require(:card).permit(:title, :content, :position, :kanban_column_id)
  end

end

app/views/cards/_card_action.html.erb
<div class="flex items-center justify-between mt-6">
  <%= link_to 'javascript:history.back()' do %>
    <%= render_button variant: :outline do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 15.75 3 12m0 0 3.75-3.75M3 12h18"/>
      </svg>
    <% end %>
  <% end %>
  <div class="flex space-x-2">
    <%= render_dialog do %>
      <%= dialog_trigger do %>
        <%= render_button("Edit", variant: :outline) %>
      <% end %>
      <%= render "cards/shared/dialog", card_action: :edit %>
    <% end %>
    <%= render_dialog do %>
      <%= dialog_trigger do %>
        <%= render_button("Delete", variant: :outline) %>
      <% end %>
      <%= render "cards/shared/dialog", card_action: :delete %>
    <% end %>
  </div>
</div>

app/views/cards/_card_comment_form.html.erb
<%= form_with url: card_comments_path, scope: :card_comment, method: :post do |form| %>
  <div class="sr-only">
    <%= form.number_field :card_id, value: @card.id %>
    <%= form.number_field :auth_id, value: current_auth.id %>
  </div>
  <div class="mt-6">
    <%= form.text_field :text, placeholder: "Write a comment", class: "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50" %>
    <%= form.submit "Comment", class: "inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2 mt-2 cursor-pointer" %>
  </div>
<% end %>

app/views/cards/_card_comments.html.erb
<section data-controller="kanban--card-comment">
  <% @card_comments.each do |card_comment| %>
    <div class="mt-6 border-t pt-6">
      <div class="flex items-center justify-between">
        <div class="flex items-center">
        <span class="relative w-10 h-10 overflow-hidden bg-gray-100 rounded-full dark:bg-gray-600">
          <svg class="absolute w-12 h-12 text-gray-400 -left-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path>
          </svg>
        </span>
          <div class="ml-2">
            <span class="block font-medium text-gray-700">
              <%= card_comment.auth.email %>
            </span>
            <span class="block text-sm text-gray-500">
              <%= card_comment.auth.profile.position ? card_comment.auth.profile.position : "Unknown Position" %>
            </span>
          </div>
        </div>
        <% if current_auth.id === card_comment.auth_id %>
          <div class="flex gap-2 items-center">
            <button data-comment-button-id="<%= card_comment.id %>" data-action="click->kanban--card-comment#toggleComment" class="text-blue-700 hover:text-blue-800">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.832 19.82a4.5 4.5 0 0 1-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 0 1 1.13-1.897L16.863 4.487Zm0 0L19.5 7.125"/>
              </svg>
            </button>
            <%= render_alert_dialog do %>
              <%= alert_dialog_trigger do %>
                <button class="text-red-700 hover:text-red-800 text-xs">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 9.75 14.25 12m0 0 2.25 2.25M14.25 12l2.25-2.25M14.25 12 12 14.25m-2.58 4.92-6.374-6.375a1.125 1.125 0 0 1 0-1.59L9.42 4.83c.21-.211.497-.33.795-.33H19.5a2.25 2.25 0 0 1 2.25 2.25v10.5a2.25 2.25 0 0 1-2.25 2.25h-9.284c-.298 0-.585-.119-.795-.33Z"/>
                  </svg>
                </button>
              <% end %>
              <%= alert_dialog_content do %>
                <div class="flex flex-col space-y-2 text-center sm:text-left text-xs">
                  <h2 class="text-lg font-semibold">Delete comment</h2>
                  <p class="text-sm text-muted-foreground">
                    This action cannot be undone.
                  </p>
                </div>
              <% end %>
              <%= alert_dialog_cancel do %>
                <%= render_button("Cancel", variant: :outline) %>
              <% end %>
              <%= alert_dialog_continue do %>
                <%= link_to card_comment_path(card_comment), data: { "turbo-method": :delete } do %>
                  <%= render_button("Yes", variant: :destructive) %>
                <% end %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="mt-2 text-sm text-gray-700"
           data-kanban--card-comment-target="comment"
           data-target-id="<%= card_comment.id %>"
           data-is-edit="false"
      >
        <span>
          <%= card_comment.text %>
        </span>
        <% if current_auth.id === card_comment.auth_id %>
          <%= form_with url: card_comment_path(card_comment), scope: :card_comment, method: :patch, class: "hidden" do |form| %>
            <%= form.text_area :text, placeholder: "Edit comment...", class: "resize-none  flex w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50" %>
            <div class="items-center mt-1 gap-2 flex justify-end">
              <%= form.submit "Save", class: "inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-blue-500 text-primary-foreground hover:bg-blue/90 cursor-pointer py-1 px-2" %>
              <button type="button" data-comment-button-id="<%= card_comment.id %>" data-action="click->kanban--card-comment#toggleComment" class="cursor-pointer inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-background hover:bg-accent hover:text-accent-foreground py-1 px-2">
                Cancel
              </button>
            </div>
            <div class="sr-only">
              <%= form.number_field :card_id, value: card_comment.card_id %>
              <%= form.number_field :auth_id, value: current_auth.id %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</section>

app/views/cards/_card_info.html.erb
<div class="flex justify-between items-start">
  <h2 class="text-2xl font-bold">
    <%= @card.title %>
  </h2>
</div>
<div class="mt-2">
  <div class="flex items-center space-x-2 text-sm text-gray-500">
    <span>Added by</span>
    <span class="font-medium text-gray-700">
      Author card here1
      <%#= @card.author.auth.username ? @card.profile.auth.username : @card.profile.auth.email %>
    </span>
    <span>
        <%= @card.created_at.strftime("%d/%m/%Y") %>
      |
      <%= @card.created_at.strftime("%H:%M  ") %>
      </span>
  </div>
  <div class="flex items-center mt-4 gap-4">
    <div class="flex -space-x-4 rtl:space-x-reverse ">
        <span class="relative w-10 h-10 overflow-hidden border border-white bg-gray-100 rounded-full dark:bg-gray-600">
          <svg class="absolute w-12 h-12 text-gray-400 -left-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path>
          </svg>
        </span>
      <span class="relative w-10 h-10 overflow-hidden border border-white bg-gray-100 rounded-full dark:bg-gray-600">
          <svg class="absolute w-12 h-12 text-gray-400 -left-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path>
          </svg>
        </span>
    </div>
    <div class="flex">
      <button class="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 hover:bg-accent h-10 px-4 py-2 text-blue-500 hover:text-blue-600">
        +
        <Join></Join>
      </button>
      <button class="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 hover:bg-accent h-10 px-4 py-2 text-blue-500 hover:text-blue-600">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
          class="h-5 w-5"
        >
          <path d="m21.44 11.05-9.19 9.19a6 6 0 0 1-8.49-8.49l8.57-8.57A4 4 0 1 1 18 8.84l-8.59 8.57a2 2 0 0 1-2.83-2.83l8.49-8.48"></path>
        </svg>
      </button>
    </div>
  </div>
</div>
<div class="mt-6">
  <h3 class="text-lg font-semibold">Description</h3>
  <p class="mt-2 text-sm text-gray-700">
    <%= @card.content %>
  </p>
  <button class="mt-2 text-sm text-blue-500 hover:text-blue-600">Show Full
    Description
  </button>
</div>

app/views/cards/_form.html.erb
<div class="w-full mx-auto">
  <div class="text-xl font-bold mb-6">Create New Task</div>
  <%= form_with model: card, method: :post, class: "grid gap-4" do |form| %>
    <div class="space-y-2">
      <%= form.label "Title", name: :title, class: "text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70" %>
      <%= form.text_field :title, class: "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50", placeholder: "Enter card title" %>
    </div>
    <div class="space-y-2">
      <%= form.label "Content", name: :content, class: "text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70" %>
      <%= form.text_area :content, class: "flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50", placeholder: "Enter card content" %>
    </div>
    <%= form.submit "Create Task", class: "cursor-pointer inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2 w-full" %>
    <div class="sr-only">
      <%= form.text_field :position, value: column.cards.length + 1 %>
      <%= form.text_field :kanban_column_id, value: column.id %>
    </div>
  <% end %>
</div>

app/views/cards/show.html.erb
<%= render 'components/ui/notice' %>
<div class="mt-16 bg-white p-6 rounded-lg shadow-lg max-w-2xl mx-auto">
  <%= render "cards/card_info" %>
  <%= render "cards/card_comment_form" %>
  <%= render "cards/card_comments" %>
  <%= render "cards/card_action" %>
</div>