config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :auths
  get '/forgot_password', to: 'passwords#forgot'
  post 'send_token', to: 'passwords#send_token'

  namespace :api do
    # auth
    resources :auths, only: :show
    get '/auths_by_email', to: 'auths_by_emails#show', as: :auths_by_email
    # kanban_assignee
    get '/kanban_assignees', to: 'kanban_assignees#get_assignees'
    post '/kanban_assignees/assign', to: 'kanban_assignees#assign'
  end

  resources :accounts
  resource :profile, only: %i[show update]

  # kanban
  resources :kanbans
  patch '/kanbans/:id/sort', to: 'kanbans#sort', as: 'kanban_sort'

  # kanban column
  resources :kanban_columns

  # card
  resources :cards

  # card comment
  resources :card_comments

  root 'home#index'
end

app/models/kanban.rb
class Kanban < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  belongs_to :author, class_name: 'Profile'
  has_many :kanban_columns, dependent: :destroy
  has_many :kanban_assignees
  has_many :profiles, through: :kanban_assignees

  after_create :assign_creator

  def assign_creator
    KanbanAssignee.create(
      kanban: self,
      profile: author
    )
  end
end

app/controllers/kanbans_controller.rb
# frozen_string_literal: true
class KanbansController < ApplicationController
  before_action :authenticate_auth!
  before_action :set_kanban, only: %i[ show sort destroy update ]

  # GET /kanbans or /kanbans.json
  def index
    @kanbans = Kanban.all
    @kanban = Kanban.new
  end

  # GET /kanbans/1 or /kanbans/1.json
  def show
    @accounts = Rails.cache.fetch('all_accounts') { Profile.with_auth }
    @kanbans = Rails.cache.fetch('all_kanbans') { Kanban.all }
    @kanban_columns = KanbanColumn.where(kanban_id: @kanban.id)
    @kanban_column = KanbanColumn.new
    @assignees = KanbanAssignee.where(kanban_id: @kanban.id)
  end

  # POST /kanbans or /kanbans.json
  def create
    profile = Profile.with_auth.find_by(auths: { email: current_auth.email })
    @kanban = Kanban.new(kanban_params.merge(author: profile))
    respond_to do |format|
      if @kanban.save!
        format.html { redirect_to kanbans_path, notice: "#{@kanban.name} was successfully created." }
        format.json { render json: @kanban, status: :created }
      else
        flash[:error] = "#{@kanban.name} couldn't created. Something went wrong!"
        format.json { render json: @kanban.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kanbans/1 or /kanbans/1.json
  def destroy
    respond_to do |format|
      if @kanban.destroy!
        format.html { redirect_to kanbans_path, notice: "#{@kanban.name} was delete!." }
        format.json { render json: @kanban, status: :no_content }
      else
        flash[:error] = "#{@kanban.name} couldn't delete. Something went wrong!"
        format.json { render json: @kanban.errors, status: :unprocessable_entity }
      end
    end
  end

  def sort
    if authorized_assignees?
      sorted_cols = JSON.parse(kanban_params['kanbanIds'])['columns']
      sorted_cols.each do |col|
        col['cardIds'].each do |card_id|
          @card = Card.find(card_id)
          @card.update!(
            kanban_column: KanbanColumn.find(col['id']),
            position: col['cardIds'].find_index(card_id)
          )
        end
      end

      respond_to do |format|
        format.json do
          render json: {
            status: 201,
            message: 'Sorted',
            isAuthorized: true
          }
        end
      end
    else
      respond_to do |format|
        format.json do
          render json: {
            status: 401,
            message: 'Unauthorization',
            isAuthorized: false
          }
        end
      end
    end
  end

  def update
    respond_to do |format|
      if @kanban.update(kanban_params)
        format.html { redirect_to kanbans_path, notice: "#{@kanban.name} was updated!" }
        format.json { render json: @kanban, status: :ok }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kanban.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def authorized_assignees?
    KanbanAssignee.where(kanban_id: @kanban.id)
                  .exists?(profile_id: current_auth.id)
  end

  def set_kanban
    @kanban = Kanban.find(params[:id])
  end

  def kanban_params
    params.require(:kanban).permit(:name, :author, :description, :kanbanIds)
  end
end

app/views/kanbans/_assignee_list.html.erb
<div class="flex -space-x-4 rtl:space-x-reverse">
  <% @assignees[0..3].each do |assignee| %>
    <% if assignee.profile.avatar.blank? %>
      <div class="flex items-center justify-center w-10 h-10 overflow-hidden bg-gray-100 border-2 border-white rounded-full cursor-pointer">
        <svg class="w-13 h-13 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path>
        </svg>
      </div>
    <% else %>
      <%= image_tag assignee.profile.avatar.variant(:thumb), class: "cursor-pointer w-10 h-10 border-2 border-white rounded-full" %>
    <% end %>
  <% end %>
  <% if @assignees.size > 4 %>
    <a class="relative flex items-center justify-center w-10 h-10 text-xs font-medium text-white bg-gray-700 border-2 border-white rounded-full hover:bg-gray-600 dark:border-gray-800" href="#">
      +<%= @assignees.size - 4 %>
    </a>
  <% end %>
</div>

app/views/kanbans/_filter_group.html.erb
<%= render_popover do %>
  <%= popover_trigger do %>
    <button
      class="inline-flex items-center text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700"
      type="button"
    >
      Select Group
      <svg
        class="w-4 h-4 ml-2" aria-hidden="true" fill="none" stroke="currentColor" viewBox="0 0 24 24"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
      </svg>
    </button>
  <% end %>
  <%= popover_content do %>
    <div class="absolute top-0 left-[-60px] z-10 w-56 p-3 bg-white rounded-lg border shadow-lg">
      <h6 class="mb-3 text-sm font-medium text-gray-900 dark:text-white">
        Group name
      </h6>
      <ul class="space-y-2 text-sm"
          aria-labelledby="dropdownDefault"
      >
        <%# form %>
        <% if @kanban_columns.size === 0 %>
        <span>
          no group
        </span>
        <% else %>
          <% @kanban_columns.each do |kanban_column| %>
            <li class="flex items-center cursor-pointer">
              <input id="<%= "#{kanban_column.name}#{kanban_column.id}" %>" type="checkbox"
                     value="
                   <%= kanban_column.id %>"
                     class="w-4 h-4 bg-gray-100 border-gray-300 rounded text-primary-600 focus:ring-primary-500 dark:focus:ring-primary-600 dark:ring-offset-gray-700 focus:ring-2 cursor-pointer"
                />
              <label for="<%= "#{kanban_column.name}#{kanban_column.id}" %>" class="ml-2 text-sm font-medium text-gray-900 cursor-pointer">
                <%= kanban_column.name %>
              </label>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/kanbans/_form_kanban.html.erb
<%= form_with(model: kanban, class: "contents", method: :post) do |form| %>
  <div class="max-w-2xl mx-auto">
    <% if kanban.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(kanban.errors.count, "error") %>
          prohibited this
          kanban
          from being saved:
        </h2>
        <ul>
          <% kanban.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="my-5">
      <%= form.label :name, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
      <%= form.text_field :name, class: "appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>
    </div>

    <div class="my-5">
      <%= form.label :description, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
      <%= form.text_area :description, size: "30x10", class: "appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>
    </div>

    <div class="inline">
      <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    </div>
  </div>
<% end %>

app/views/kanbans/_form_modal.html.erb
<!-- Modal toggle -->
<button data-modal-target="crud-modal" data-modal-toggle="crud-modal" class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" type="button">
  Toggle modal
</button>

<!-- Main modal -->
<div id="crud-modal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
  <div class="relative p-4 w-full max-w-md max-h-full">
    <!-- Modal content -->
    <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
      <!-- Modal header -->
      <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
        <h3 class="text-lg font-semibold text-gray-900 dark:text-white">
          Create New Product
        </h3>
        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-toggle="crud-modal">
          <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
          </svg>
          <span class="sr-only">Close modal</span>
        </button>
      </div>
      <!-- Modal body -->
      <form class="p-4 md:p-5">
        <div class="grid gap-4 mb-4 grid-cols-2">
          <div class="col-span-2">
            <label for="name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Name</label>
            <input type="text" name="name" id="name" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Type product name" required="">
          </div>
          <div class="col-span-2 sm:col-span-1">
            <label for="price" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Price</label>
            <input type="number" name="price" id="price" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="$2999" required="">
          </div>
          <div class="col-span-2 sm:col-span-1">
            <label for="category" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Category</label>
            <select id="category" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500">
              <option selected="">Select category</option>
              <option value="TV">TV/Monitors</option>
              <option value="PC">PC</option>
              <option value="GA">Gaming/Console</option>
              <option value="PH">Phones</option>
            </select>
          </div>
          <div class="col-span-2">
            <label for="description" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Product
              Description</label>
            <textarea id="description" rows="4" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Write product description here"></textarea>
          </div>
        </div>
        <button type="submit" class="text-white inline-flex items-center bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
          <svg class="me-1 -ms-1 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z" clip-rule="evenodd"></path>
          </svg>
          Add new product
        </button>
      </form>
    </div>
  </div>
</div>

app/views/kanbans/_kanban_cards_list.html.erb
<div class="overflow-x-scroll min-h-[80vh] mt-8"
     data-controller="kanban--card-dragndrop"
>
  <div class="flex justify-start items-start gap-4 mb-3 px-6"
       data-kanban--card-dragndrop-target="kanbanGroup"
       data-kanban-id="<%= @kanban.id %>"
       data-current-user-id="<%= current_auth.id %>"
  >
    <% @kanban_columns.each do |column| %>
      <div class="flex flex-col py-1">
        <div class="flex justify-between items-center relative">
          <%= tag.p column.name, class: "font-bold text-base" %>
          <div class="flex items-center gap-2">
            <%= render "kanban_columns/shared/dialog_edit", column: column %>
            <%= link_to kanban_column_path(column.id), data: { "turbo-method": :delete }, class: "bg-red-100 text-red-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded hover:bg-red-200" do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 9.75 14.25 12m0 0 2.25 2.25M14.25 12l2.25-2.25M14.25 12 12 14.25m-2.58 4.92-6.374-6.375a1.125 1.125 0 0 1 0-1.59L9.42 4.83c.21-.211.497-.33.795-.33H19.5a2.25 2.25 0 0 1 2.25 2.25v10.5a2.25 2.25 0 0 1-2.25 2.25h-9.284c-.298 0-.585-.119-.795-.33Z"/>
              </svg>
            <% end %>
          </div>
        </div>
        <div class="min-w-[28rem] w-[28rem] py-4 "
             data-kanban--card-dragndrop-target="kanbanColumn"
             data-kanban-col-id="<%= column.id %>"
        >
          <% column.cards.sort_by { |card| card.position }.each do |card| %>
            <%= link_to card_path(card.id), class: "block w-full p-6 mb-4 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700", data: { "kanban-card-id": "#{card.id}", "kanban--card-dragndrop-target": "kanbanCard" } do %>
              <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                <%= card.title %>
              </h5>
              <p class="font-normal text-gray-700 dark:text-gray-400">
                <%= card.content %>
              </p>
            <% end %>

          <% end %>
        </div>
        <%= render_dialog do %>
          <%= dialog_trigger do %>
            <button class="min-w-[28rem] w-[28rem] border-dashed border-2 border-gray-200 rounded-md font-bold p-4 hover:bg-gray-100 hover:border-gray-300">
              + Add another card
            </button>
          <% end %>
          <%= dialog_content do %>
            <%= render "cards/shared/form", card: Card, column: column, action: :post %>
          <% end %>
        <% end %>
      </div>
    <% end %>
    <div class="flex flex-col w-full">
      <div class="font-bold text-base">
        Add another group
      </div>
      <div class="min-w-[28rem] w-[28rem] py-6">
        <%= render "kanban_columns/shared/dialog_create", kanban_column: @kanban_column %>
      </div>
    </div>
  </div>
</div>

app/views/kanbans/_kanban_error.html.erb
<% if @kanbans.empty? %>
  <div class="flex items-center max-w-lg mt-16   mx-auto p-4 mb-4 text-sm text-blue-800 border border-blue-300 rounded-lg bg-blue-50" role="alert">
    <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
      <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
    </svg>
    <span class="sr-only">Info</span>
    <div>
        <span class="font-medium">
          There is no project now
        </span>
    </div>
  </div>
<% end %>

app/views/kanbans/_kanban_list.html.erb
<div class="grid grid-cols-2 md:grid-cols-4 mx-32 mt-16 gap-4">
  <% @kanbans.each do |kanban| %>
    <div class="flex flex-col p-4 rounded-lg bg-white border shadow-sm rounded-xl justify-between min-h-[240px]">
      <div class="relative">
        <h3 class="text-2xl font-bold text-gray-800 ">
          <%= kanban.name %>
        </h3>
        <p class="mt-1 text-gray-500">
          <%= kanban.description %>
        </p>
        <span class="mt-1 text-gray-500 text-xs">
            Created by:
          <%= link_to "#{kanban.author&.username.present? ? kanban.author.username : kanban.author&.auth&.email}", account_path(kanban.author.id), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
          </span>
      </div>
      <div class=" flex justify-between">
        <%= link_to "Go to", kanban_path(kanban), class: "py-2 px-3 inline-flex justify-center items-center gap-x-2 text-sm font-semibold rounded-lg border border-transparent bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50 disabled:pointer-events-none" %>
        <div class="flex gap-2">
          <%= render "kanbans/shared/dialog_edit", kanban: kanban %>
          <%= render "kanbans/shared/dialog_delete", kanban: kanban %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/kanbans/_select_assignee.html.erb
<% isAuthorized = current_auth.id === @kanban.author_id %>

<%= render_dialog do %>
  <%= dialog_trigger do %>
    <button
      class="inline-flex gap-2 items-center text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-5 py-2"
      type="button"
    >
      Assign User
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M18 7.5v3m0 0v3m0-3h3m-3 0h-3m-2.25-4.125a3.375 3.375 0 1 1-6.75 0 3.375 3.375 0 0 1 6.75 0ZM3 19.235v-.11a6.375 6.375 0 0 1 12.75 0v.109A12.318 12.318 0 0 1 9.374 21c-2.331 0-4.512-.645-6.374-1.766Z"/>
      </svg>
    </button>

  <% end %>

  <%= dialog_content do %>
    <span>Assignees List</span>
    <section data-controller="kanban--select-assignee">
      <div
        class="flex"
        data-kanban-id="<%= @kanban.id %>"
        data-kanban--select-assignee-target="selection"
      ></div>
      <label for="select-assignee-input"></label>
      <div class="flex space-x-2 mt-4">
        <input
          id="select-assignee-input"
          class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 max-w-lg flex-1"
          placeholder="Enter email addresses"
          type="email"
          data-kanban--select-assignee-target="input"
        >
      </div>
      <div class="relative flex flex-col gap-4 overflow-y-scroll max-h-[280px] py-2"
           data-kanban--select-assignee-target="list"
      >
        <% @accounts.each do |account| %>
          <div class="flex items-center gap-3"
               data-kanban--select-assignee-target="item"
               data-item-account-id="<%= account.id %>"
          >
            <div class="relative w-10 h-10 overflow-hidden bg-gray-100 rounded-full dark:bg-gray-600">
              <% if account.avatar.blank? %>
                <svg class="absolute w-12 h-12 text-gray-400 -left-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path>
                </svg>
              <% else %>
                <%= image_tag account.avatar.variant(:thumb), class: "w-10 h-10 rounded-full" %>
              <% end %>
            </div>
            <div class="grid gap-0.5 text-xs">
              <% if account.name %>
                <div class="font-medium">
                  <%= account.name %>
                </div>
              <% end %>
              <div class="text-gray-500 dark:text-gray-400">
                <%= account.auth.email %>
              </div>
            </div>
            <% if current_auth.id === account.id %>
              <span class="ml-auto mr-3 cursor-default bg-gray-100 text-gray-800 text-xs font-medium px-2.5 py-0.5 rounded">You</span>
            <% end %>
            <button
              data-kanban--select-assignee-target="itemButton"
              data-item-button-id="<%= account.id %>"
              data-action="click->kanban--select-assignee#select"
              data-item-is-add="false"
              class="relative ml-auto mr-3 group <%= 'hidden' if current_auth.id === account.id %> <%= 'cursor-not-allowed' if current_auth.id != @kanban.author_id %>" type="button"
              <%= :disabled if current_auth.id != @kanban.author_id %>
            >
              <svg data-select-icon="iconAdd" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 group-hover:text-red-700">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
              </svg>
              <svg data-select-icon="iconCheck" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-green-500 group-hover:text-green-700 hidden">
                <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 12.75 6 6 9-13.5"/>
              </svg>
            </button>
          </div>
        <% end %>
      </div>
      <button
        class="relative flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium w-full ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2 <%= 'cursor-not-allowed' unless isAuthorized %>"
        type="submit"
        data-action="click->kanban--select-assignee#save mouseover->kanban--select-assignee#tooltipShow mouseout->kanban--select-assignee#tooltipShow"
        data-is-authorized="<%= isAuthorized %>"
      >
        Save
      </button>
      <% unless isAuthorized %>
        <div data-kanban--select-assignee-target="tooltip" role="tooltip" class="absolute hidden z-500 inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-sm bottom-20 left-[50%] translate-x-[-50%] whitespace-nowrap">
          You have to be creator to assign
        </div>
      <% end %>
      <template id="assigneeInput">
        <input data-kanban--select-assignee-target="selectionInput" type="text" multiple="multiple" hidden name="kanban_assignee[assignees][]"/>
      </template>
    </section>
  <% end %>
<% end %>

<%= turbo_stream.prepend "flash", "components/partial/flash" %>

app/views/kanbans/index.html.erb
<section class="w-full">
  <%= render 'kanbans/shared/kanban_head' %>
  <%= render "components/ui/notice" %>
  <%= render "kanban_error" %>
  <%= render "kanban_list" %>
</section>

app/views/kanbans/new.html.erb
<div class="mx-auto w-full">
  <h1 class="max-w-2xl mx-auto block uppercase tracking-wide text-gray-700 font-bold text-4xl">
    Create new Kanban Project
  </h1>
  <%= render "form_kanban", kanban: @kanban %>
</div>

app/views/kanbans/show.html.erb
<section>
  <%= render 'kanbans/shared/kanban_head' do %>
    <%= render "kanbans/shared/select_kanban" %>
  <% end %>

  <%= render "components/ui/notice" %>

  <div class="flex items-center gap-2 px-6 py-3">
    <%= render "filter_group" %>
    <%= render "select_assignee" %>
  </div>
  <div class="flex items-center gap-2 px-6">
    <%= render "assignee_list" %>
  </div>

  <%= render "kanban_cards_list" %>
</section>